apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsvp-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsvp-web
  template:
    metadata:
      labels:
        app: rsvp-web
    spec:
      containers: 
      - name: rsvpd-web
        image: paichayon/rsvp:nginx-rewrite
        env:
        - name: MONGODB_HOST
          value: mongodb
        - name: COMPANY
          value: "**** Lab8088 Prod ****"
        - name: TEXT1
          value: "ArgoCD Training  "
        - name: TEXT2
          value: " Application"
        - name: LOGO
          value: https://raw.githubusercontent.com/paichayon321/argocd101-application/main/images/argocd-kube-image250.png
        ports:
        - containerPort: 5000
          name: web-port    
