apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: read-secret-role
    serviceAccount: vault-serviceaccount
    audiences:
      - vault
