apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-app
spec:
  type: kv-v2

  # mount path
  mount: secret/vso

  # path of the secret
  path: mysecret

  # dest k8s secret
  destination:
    name: kubesecret-mysecret
    create: true

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: static-auth
