apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsvp-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsvp-web
  template:
    metadata:
      labels:
        app: rsvp-web
    spec:
      serviceAccountName: vault-serviceaccount
      containers: 
      - name: rsvpd-web
        image: paichayon/rsvp:readsecret
        volumeMounts:
         - name: secret-volume
           mountPath: "/vault/secrets/"  # The directory where secrets will be mounted
           readOnly: true
        env:
        - name: MONGODB_HOST
          value: mongodb
        - name: COMPANY
          value: "**** Lab8088 Company ****"
        - name: TEXT1
          value: "ArgoCD Training  "
        - name: TEXT2
          value: " Application"
        - name: LOGO
          value: https://argo-cd.readthedocs.io/en/stable/assets/logo.png
        - name: username
          valueFrom:
            secretKeyRef:
               name: kubesecret-my-first-secret
               key: username
        - name: password
          valueFrom:
            secretKeyRef:
               name: kubesecret-my-first-secret
               key: password 
        ports:
        - containerPort: 5000
          name: web-port  
      volumes:
        - name: secret-volume
          secret:
            secretName: kubesecret-my-first-secret
