apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-username: bW9uZ29hZG1pbg==  # Base64 for 'mongoadmin'
  mongo-password: c2VjcmV0cGFzc3dvcmQ=  # Base64 for 'secretpassword'
