apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsvp-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsvp-db
  template:
    metadata:
      labels:
        app: rsvp-db
    spec:
      containers: 
      - name: rsvpd-db
        image: mongo:6.0
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-password
        volumeMounts:
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
        ports:
        - containerPort: 27017
      volumes:
      - name: init-script
        configMap:
          name: mongodb-init-script
