apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsvp-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsvp-web
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-login: "secret/login"
        vault.hashicorp.com/agent-inject-template-login: |
          {{- with secret "secret/login" -}}
          export pattoken={{ .Data.data.pattoken }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-my-first-secret: "secret/my-first-secret"
        vault.hashicorp.com/agent-inject-template-my-first-secret: |
          {{- with secret "secret/my-first-secret" -}}
          export username={{ .Data.data.username }}
          export password={{ .Data.data.password }}
          {{- end }}
        vault.hashicorp.com/role: "vault-role"
      labels:
        app: rsvp-web
    spec:
      serviceAccountName: vault-serviceaccount
      containers: 
      - name: rsvp-web
        image: paichayon/rsvp:nginx-rewrite
        env:
        - name: MONGODB_HOST
          value: mongodb
        - name: COMPANY
          value: "**** Lab8088 Company ****"
        - name: TEXT1
          value: "ArgoCD Training  "
        - name: TEXT2
          value: " Application"
        - name: LOGO
          value: https://argo-cd.readthedocs.io/en/stable/assets/logo.png
        - name: pottoken
          value: /vault/secrets/login
        - name: username
          value: /vault/secrets/my-first-secret 
        ports:
        - containerPort: 5000
          name: web-port
