resources:
- ../../base
- sealed-mysecret.yaml
patches:
- path: patch-rsvp-web-deployment.yaml
- path: patch-rsvp-ingress.yaml


configMapGenerator:
- name: rsvp-web-config
  envs:
     - env.config
# Add sealed secret file to configmap and at deployment reference both secret name and configmap
- name: mysecret
  files:
    - sealed-mysecret.yaml

